defaults:
  - logger: logger
  - arch: anakin
  - system: ramdp_vpg/ff_reinforce_explicit_cot
  - network: transformer_explicit_cot
  - env: gymnax/cartpole
  - _self_

hydra:
  searchpath:
    - file://stoix/configs
