"""Lights Out puzzle environment, natively Stoa-compatible.

The classic "Lights Out" puzzle on an `m x n` grid: each cell is a light,
either on (1) or off (0). Pressing a cell toggles it and its orthogonal
neighbours. The agent must press cells (one per step) to turn the grid from
its randomly-generated `initial` pattern into a randomly-generated `goal`
pattern.

`goal` is generated by applying a random sequence of `dist` presses (in
GF(2), press order doesn't matter, only the multiset of pressed cells mod 2 -
see `_reset_with_dist`) to `initial`, so `goal` is always reachable from
`initial` in exactly `dist` presses (fewer is possible if some are
redundant/cancel out). `dist` is sampled per episode: from `[1, threshold)`
during training (`eval=False`) - "easy" instances - and from
`[threshold, grid_size)` during evaluation (`eval=True`) - "hard" instances -
so the agent trains on shorter solution paths and is evaluated on harder
ones, per `config.difficulty_threshold`.

The observation is `(m, n, 2)`: the current grid and the goal grid, each
reshaped to `(m, n)` and stacked as two channels (channel-last, matching
`stoix.networks.torso.CNNTorso`'s expected `(H, W, C)` input) - without the
goal, the task has no observable target and is unsolvable by construction.
Non-CNN torsos flatten this via `stoa.FlattenObservationWrapper`, exactly
like the grid-observation environments in `ramdp_experiments/
minatar_fixed_budget_sweep.py`.

Source: https://rajghugare19.github.io/computation-rl/index.html
"""

from typing import Any, Optional, Tuple

import jax
import jax.numpy as jnp
import numpy as np
from flax import struct
from ml_collections import config_dict
from stoa.env_types import Action, EnvParams, StepType, TimeStep
from stoa.environment import Environment
from stoa.spaces import BoundedArraySpace, DiscreteSpace, Space


@struct.dataclass
class LightsOutData:
    grid: jax.Array
    goal: jax.Array


@struct.dataclass
class State:
    """Environment state carried between steps (everything needed to keep
    stepping - the actual observation/reward/discount live in the `TimeStep`
    returned alongside this, per the Stoa `Environment` interface)."""

    data: LightsOutData
    step_count: jax.Array


def default_config() -> config_dict.ConfigDict:
    config = config_dict.create(
        m=3,
        n=3,
        episode_length=6,
        difficulty_threshold=0.5,  # <--- Goals with < 4 toggles are "Easy"
    )
    return config


class LightsOutEnv(Environment):
    """Lights Out puzzle. `eval=True` samples harder (higher-`dist`) goals,
    for use as the evaluation instance alongside a separate `eval=False`
    training instance - see module docstring."""

    def __init__(self, config: config_dict.ConfigDict = default_config(), eval: bool = False):
        super().__init__()
        self._config = config
        self._eval = eval
        self.m, self.n = config.m, config.n
        self.grid_size = self.m * self.n
        self.threshold = int(self.grid_size * config.difficulty_threshold)

        # Pre-compute action matrix: matrix[i, j] = 1 if button i toggles button j
        self.action_matrix = self._create_action_matrix()

    def _create_action_matrix(self) -> jnp.ndarray:
        matrix = np.zeros((self.grid_size, self.grid_size), dtype=np.int32)
        for i in range(self.grid_size):
            r, c = i // self.n, i % self.n
            matrix[i, i] = 1  # Toggle self
            if r > 0:
                matrix[i, (r - 1) * self.n + c] = 1  # Up
            if r < self.m - 1:
                matrix[i, (r + 1) * self.n + c] = 1  # Down
            if c > 0:
                matrix[i, r * self.n + (c - 1)] = 1  # Left
            if c < self.n - 1:
                matrix[i, r * self.n + (c + 1)] = 1  # Right
        return jnp.array(matrix)

    def reset(
        self, rng_key: jax.Array, env_params: Optional[EnvParams] = None
    ) -> Tuple[State, TimeStep]:
        rng_dist, rng_reset = jax.random.split(rng_key)

        # "Easy" distances for training, "hard" distances for evaluation - see
        # module docstring.
        if self._eval:
            dist = jax.random.randint(rng_dist, (), self.threshold, self.grid_size)
        else:
            dist = jax.random.randint(rng_dist, (), 1, self.threshold)

        return self._reset_with_dist(rng_reset, dist)

    def _reset_with_dist(self, rng: jax.Array, dist: jax.Array) -> Tuple[State, TimeStep]:
        key_init, key_actions = jax.random.split(rng)

        initial = jax.random.bernoulli(key_init, shape=(self.grid_size,)).astype(jnp.int32)

        # Create action coefficients with exactly 'dist' number of ones
        indices = jax.random.permutation(key_actions, self.grid_size)
        mask = jnp.arange(self.grid_size) < dist
        action_coeffs = jnp.zeros(self.grid_size, dtype=jnp.int32).at[indices].set(mask)

        goal = (initial + jnp.dot(self.action_matrix.T, action_coeffs)) % 2

        data = LightsOutData(grid=initial.astype(jnp.float32), goal=goal.astype(jnp.float32))
        state = State(data=data, step_count=jnp.array(0, dtype=jnp.int32))

        timestep = TimeStep(
            step_type=StepType.FIRST,
            reward=jnp.array(0.0, dtype=jnp.float32),
            discount=jnp.array(1.0, dtype=jnp.float32),
            observation=self._make_observation(data),
            extras={"target_goal": data.goal},
        )
        return state, timestep

    def _make_observation(self, data: LightsOutData) -> jax.Array:
        return jnp.stack(
            [data.grid.reshape(self.m, self.n), data.goal.reshape(self.m, self.n)], axis=-1
        )

    def step(
        self, state: State, action: Action, env_params: Optional[EnvParams] = None
    ) -> Tuple[State, TimeStep]:
        data = state.data

        # Apply toggle pattern (action is an integer index)
        toggle_pattern = self.action_matrix[action]
        new_grid = (data.grid.astype(jnp.int32) + toggle_pattern) % 2

        new_data = LightsOutData(grid=new_grid.astype(jnp.float32), goal=data.goal)
        new_step_count = state.step_count + 1
        new_state = State(data=new_data, step_count=new_step_count)

        # Solved if the grid now matches the goal.
        success = jnp.all(new_grid == data.goal.astype(jnp.int32))

        # reward = 1.0 if solved, else a small penalty to encourage speed
        reward = success.astype(jnp.float32) - 0.1

        terminated = success
        truncated = (new_step_count >= self._config.episode_length) & (~terminated)
        step_type = jnp.where(
            terminated,
            StepType.TERMINATED,
            jnp.where(truncated, StepType.TRUNCATED, StepType.MID),
        )
        discount = jnp.where(terminated | truncated, 0.0, 1.0).astype(jnp.float32)

        timestep = TimeStep(
            step_type=step_type,
            reward=reward,
            discount=discount,
            observation=self._make_observation(new_data),
            extras={"target_goal": new_data.goal},
        )
        return new_state, timestep

    def observation_space(self, env_params: Optional[EnvParams] = None) -> Space:
        return BoundedArraySpace(
            shape=(self.m, self.n, 2),
            dtype=jnp.float32,
            minimum=0.0,
            maximum=1.0,
            name="observation",
        )

    def action_space(self, env_params: Optional[EnvParams] = None) -> Space:
        return DiscreteSpace(num_values=self.grid_size, dtype=jnp.int32, name="action")

    def state_space(self, env_params: Optional[EnvParams] = None) -> Space:
        return BoundedArraySpace(
            shape=(self.m, self.n, 2), dtype=jnp.float32, minimum=0.0, maximum=1.0, name="state"
        )
